pool:
  name: Latest Windows pool
  vmImage: windows-latest

trigger: none

pr: none

variables:
  IxDevOpsBuild: true
  system.debug: false

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore interdependencies (project system)'
  inputs:
    command: restore
    projects: src/IX.Abstractions.sln
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  displayName: 'Build in release'
  inputs:
    projects: src/IX.Abstractions.sln
    arguments: '-c Release'

- task: ChangelogGenerator@1
  inputs:
    workingDir: 'doc'
    filename: 'Changelog.md'
    commits: 'false'

- task: CopyFiles@2
  displayName: 'Copy artifacts'
  inputs:
    Contents: |
      src/**/*.nupkg
      src/**/*.snupkg
    TargetFolder: '$(Build.ArtifactStagingDirectory)/nuget/'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish NuGet package artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/nuget'
    ArtifactName: NuGet