pool:
  name: Latest Windows pool
  vmImage: windows-latest

trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

pr:
  autoCancel: true
  branches:
    include:
    - dev
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

variables:
  IxDevOpsBuild: true
  IxVersionPrefix: 0.5.0
  IxVersionSuffix:
  system.debug: false

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore interdependencies (project system)'
  inputs:
    command: restore
    projects: src/IX.Abstractions.sln
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  displayName: 'Build in debug'
  inputs:
    projects: src/IX.Abstractions.sln
    arguments: '-c Debug --version-suffix alpha'